### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by d0ugal** [jxwolstenholme/btsmarthub_devicelist#2]
Seen this a few times in my HA log.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/__init__.py", line 709, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bt_smarthub.py", line 53, in scan_devices
    self._update_info()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bt_smarthub.py", line 71, in _update_info
    data = self.get_bt_smarthub_data()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/device_tracker/bt_smarthub.py", line 84, in get_bt_smarthub_data
    router_ip=self.host, only_active_devices=True)
  File "/usr/local/lib/python3.6/site-packages/btsmarthub_devicelist/btsmarthub_devicelist.py", line 153, in get_devicelist
    devicelist = deviceresponse.json()['reply']['actions'][0]['callbacks'][0]['parameters']['value']
IndexError: list index out of range
```

**Comment by jxwolstenholme** [comment]
Otherwise does it seem to be working fine?
I think maybe the best thing is for me to just add a try/except clause if it only happens on rare-ish occasions.

**Comment by d0ugal** [comment]
Yup, I am not aware of any issues. It seems to still be working great, I guess maybe just some updates fail?

So yeah, a try/except is probably a good enough fix!
